name: Docker

on: push

env:
  IMAGE: ${{ github.repository  }}

jobs:
  builder:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout to Repository
        uses: actions/checkout@v2

      - name: Login to registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_SECRET  }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.IMAGE  }}:latest
